ingress:
  enabled: true
  ingressClassName: nginx
  path: /grafana
  hosts:
    - localhost

grafana.ini:
  server:
    domain: localhost
    root_url: http://localhost:30123/grafana
    serve_from_sub_path: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway.logging
        access: proxy
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring:80
        access: proxy